### ISSUE TITLE
Missing files on pip package?

### ISSUE THREAD

**Issue by daniloandrademendes** [dfunckt/django-rules#101]
Hello.

I tried to get started from using django-rules on my project, and, for that, I've installed it using the `pip install rules` command, as specified in README. When I tried to import RulesModel, I realised that rules.contrib.models is missing.

Is the package that I've installed wrong? Do I have to install another package to have RulesModel feature? Is this a bug?

Thank you!

**Comment by efficiosoft** [comment]
Which version of rules are you using? `rules.contrib.models` has been introduced in v2.1 yesterday.

**Comment by daniloandrademendes** [comment]
I think that was a pip/cache related issue, because even installing yesterday after the release, the installed version was 2.0.1.

Sorry for the inconvenience.
