### ISSUE TITLE
Django 3.0 compatibility

### ISSUE THREAD

**Issue by rixx** [dfunckt/django-rules#111]
Django 3.0 does not include `available_attrs` anymore, which is currently imported, but unused. (A derp on my part, apologies.)

**Comment by jieter** [comment]
It would be nice to get this released: It's the final blocker for us to upgrade to Django 3.0.

**Comment by dyve** [comment]
@dfunckt Could we have a release to PyPI please? This is blocking the upgrade to Django 3.

**Comment by dfunckt** [comment]
v2.2.0 should support Django 3.0. Apologies for the delay getting back to you all.

**Comment by timwilson** [comment]
@dfunckt Do you have an ETA for the 2.2.0 release? I need to decide if I will be able to use django-rules on my project. I will happily send beer and pizza if that would help! :-)

**Comment by dfunckt** [comment]
v2.2.0 has been out for a while now.

**Comment by timwilson** [comment]
@dfunckt Thanks. I didn't see it as an available release on GitHub.

**Comment by dfunckt** [comment]
Indeed, it wasn't available on Github -- I published it after I saw your first comment and checked and found the v2.2.0 release was still a "Draft". The tag was already there though and the package was published to PyPi on January, so a `pip install rules` would get v2.2.0.
