### ISSUE TITLE
can I set a rule that only cares abt the attribtues of the object but not the user?

### ISSUE THREAD

**Issue by simkimsia** [dfunckt/django-rules#119]
let's say I have a rule taht is the below

```python

@rules.predicate
def is_assignable(user, instance):
    return instance.status == "gr_incomplete"
```
Can I simply have a rule that ignores the user? ANd do I still have to mock up a request and user in order to run unit tests for this?

**Comment by dfunckt** [comment]
Yes, `user` can be ignored. Regarding mocking, it depends on what you are testing. Do you have an example of such a test?

**Comment by dfunckt** [comment]
I see. If you don't care about actually checking permissions (ie. permission backends other than the one prodiced by Rules) you could call [`has_perm`](https://github.com/dfunckt/django-rules/blob/master/rules/permissions.py#L23) directly from your serializers. Like so:

```python
    def get_is_assignable(self, instance):
        return has_perm("vendors.assign_ir", None, instance)
    ...
```

**Comment by simkimsia** [comment]
Thanks for reply. I just tried this and I get an issue with `has_perm` being undefined. I tried to use ModelBackend but it assumes that the user is an actual object and not None.

What can I do to make it such that the only check is the one provided by Rules and only that?

**Comment by simkimsia** [comment]
Ok i got it to work

Just use the `rules.has_perm`

```python

import rules

class ReadASPQuotationSerializer:
    def get_pr_assignable(self, instance):
        return rules.has_perm("vendors.assign_pr", None, instance)

```
