### ISSUE TITLE
Missing decorator for views?

### ISSUE THREAD

**Issue by Jefffrey** [dfunckt/django-rules#12]
In the documentation it's not specified how to limit a view to users that have object based permissions. Just like normally we can do:

    @permission_required('app.action_object')
    def my_view(request, ...):
        pass

I think that we should be able to somehow take incoming object IDs arguments and automatically block the request if the user does not meet the requirements.

For example, something along the lines of:

    @permission_required('app.view_posts', 'post_id')
    def view_post(request, post_id):
        pass

What do you think?

**Comment by Visgean** [comment]
Django guardian uses something similar: https://django-guardian.readthedocs.org/en/v1.2/userguide/check.html#using-decorators though it does kind of awkward...

**Comment by dfunckt** [comment]
Fixed in 96e1212. Documentation forthcoming.
