### ISSUE TITLE
Method to list all predicates/rules?

### ISSUE THREAD

**Issue by benwhalley** [dfunckt/django-rules#122]
Is there way to list all registered predicates/rules, e.g. for the purposes of documenting permissions?

**Comment by dfunckt** [comment]
Yes, rules are registered in rulesets which are regular dicts. So you just need to import the ruleset and iterate over its keys/values. The permissions ruleset can be imported as `from rules.permissions import permissions`.

**Comment by benwhalley** [comment]
Cool - thanks.
