### ISSUE TITLE
Support Django 4.0

### ISSUE THREAD

**Issue by uri-rodberg** [dfunckt/django-rules#152]
rules doesn't support Django 4.0

```python
from django.utils.encoding import force_text
```

https://docs.djangoproject.com/en/4.0/releases/4.0/

`django.utils.encoding.force_text() and smart_text() are removed.`

**Comment by uri-rodberg** [comment]
https://docs.djangoproject.com/en/4.0/releases/3.0/#deprecated-features-3-0

`The smart_text() and force_text() aliases (since Django 2.0) of smart_str() and force_str() are deprecated. Ignore this deprecation if your code supports Python 2 as the behavior of smart_str() and force_str() is different there.`

**Comment by uri-rodberg** [comment]
Just replace `force_text` with `force_str` in `contrib/views.py`.

**Comment by jieter** [comment]
This is fixed by #153, it would be nice to have this available in a release now that django 4.0 is released.

**Comment by sergioisidoro** [comment]
Also tests are failing due to:
```
ImportError: cannot import name 'url' from 'django.conf.urls' (/home/runner/work/django-rules/django-rules/.tox/packaging/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

Since `url` is deprecated in 4.0

**Comment by dfunckt** [comment]
[v3.1.0](https://github.com/dfunckt/django-rules/releases/tag/v3.1.0) was just published, will soon be on PyPi too. Apologies for the delay. Thanks folks!
