### ISSUE TITLE
Consider cutting a new release?

### ISSUE THREAD

**Issue by namoshizun** [dfunckt/django-rules#187]
Hi, the master branch has supported [Django 5.0 and Python 3.11+](https://github.com/dfunckt/django-rules/commit/fba18e9e983de6b17137ef7a318219f02f267e98) but the latest release is still 2 years ago. Could you cut a new release?

**Comment by federicobond** [comment]
@dfunckt do you think we might be able to automate this with [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish) and trusted publishing?

**Comment by dfunckt** [comment]
@federicobond I’ve already setup this action which is triggered every time a GitHub release is made.

To cut a new release we need a PR like #166 and a GitHub release after it’s merged. The action will then publish the release to PyPi.

**Comment by dfunckt** [comment]
@federicobond do you want to have a go at it? Otherwise I’ll do it later in the day.

**Comment by federicobond** [comment]
Sure! I've just opened https://github.com/dfunckt/django-rules/pull/188

**Comment by dfunckt** [comment]
Thank you! Let’s merge and see how publishing works, it’s been a while since the last release and might need updating.

**Comment by dfunckt** [comment]
Publishing failed -- I'm taking a look.

**Comment by dfunckt** [comment]
All done -- v3.4.0 has been published. Thank you @federicobond!

And thank you @namoshizun for prodding!
