### ISSUE TITLE
Is it time for a new release ?

### ISSUE THREAD

**Issue by ticosax** [dfunckt/django-rules#22]
Hi @dfunckt,
I'm a happy user of the master branch for several month now. 
I think `django-rules` is stable and mature feature wised to be released and pushed to pypi.

Let me know if you need help.

**Comment by dfunckt** [comment]
Hi Nicolas, it's on [pypi](https://pypi.python.org/pypi?:action=display&name=rules) since 0.1 (as `rules` though -- `django-rules` is taken!). I only want to add view decorators before calling it a 1.0, which will happen soon :)

**Comment by ticosax** [comment]
oops. sorry.
Something probably went wrong in my virtualenv, and I assumed it wasn't released yet.
thank you.
