### ISSUE TITLE
persistence

### ISSUE THREAD

**Issue by highpost** [dfunckt/django-rules#34]
I'm new to django-rules. I like its simplicity and it's always helpful when there's more documentation than code. But I'm wondering how I should handle an app where I spin up a bunch of objects, each with its own set of permissions (and these are added to by users as time goes by) and, well, my server goes down. How do I rebuild that permission structure?

I (really) like that django-rules doesn't require a database hit each time I make a permission check, but its also important to record those permissions.

Thanks.

**Comment by dfunckt** [comment]
Hey @highpost, you *will* need to store the permissions somewhere in this case -- either as Django's permissions, or in another model that codifies specifically the information.

The benefits of rules are most apparent when you can infer the permissions via the relationships of your models, for example you can infer that a user is a post's author via the post's relation to the Author/User model, therefore this user can edit the post.
