### ISSUE TITLE
help w/ example for docs

### ISSUE THREAD

**Issue by highpost** [dfunckt/django-rules#35]
Hi @dfunckt, I've been building a test application w/ rules that I ultimately want to submit as a pull request. You can look at it in https://github.com/highpost/rules-testapp. It's a simple blog app with a number of users with different privilege levels.

I'm also writing an article that you can either use in your documentation or we can find another home. The first chunk (in explore.txt) is an overview of basic Django permissions. I'll get to rules after that.

My problem now is that my app works ... except with rules. If you look at views.py, you'll see that I'm using CBVs. If you remove PermissionRequiredMixin from each view, you can use the various test URLs in the README.txt file without any problem. But if you include them, then the buttons that access the views will fail with "127.0.0.1 redirected you too many times." I haven't had any luck tracking this down. I will note that the CreateView seems to work, and DetailView, UpdateView and DeleteView (with all take pk arguments) fail.

Thanks for your help.

**Comment by dfunckt** [comment]
Hey, that's awesome! From a brief look over the code (on mobile) I suspect you're forgetting to import your app's rules.py. If that's true, given that (1) rules auth backend returns False if it doesn't know of any perm with the given name and (2) the view you redirect via LOGIN_REDIRECT_URL is permission protected, so it redirects to login view, which redirects back because you're logged in already.

Try either using the autodiscover App entry, or importing rules.py somewhere convenient.

Anyhow I'll take a closer look tomorrow

**Comment by raratiru** [comment]
Hallo, please do not delete https://github.com/highpost/rules-testapp !

It has just solved a silly question I had, since I saw rules.py in the context of a real app.

**Comment by highpost** [comment]
Thanks. That fixed it and I updated the repo. To be honest, I don't think I've exercised the predicate and permissions in rules.py. I'll try that tomorrow.

I want to expand the example to test whether an entry is for a certain "topic" in the headline. Then some editors would have full permissions for "Cheese" headlines and others would have full permissions for "Cars" headlines.

**Comment by highpost** [comment]
It looks like I have a problem. The ListView template has 13 buttons:

    View  Edit  Delete    # entry 1 created by user1
    View  Edit  Delete    # entry 2 created by user1
    View  Edit  Delete    # entry 3 created by user2
    View  Edit  Delete    # entry 4 created by user4
    Create

If I login as user1, I can use the Edit and Delete buttons on entries 1 and 2, but not 3 and 4. All of the View buttons fail. I'm not sure about the View buttons, but it seems like the permissions aren't being used for entries 1 and 2, just the ownership logic in the template.

Any ideas?

**Comment by dfunckt** [comment]
You're not testing for *object* permissions -- you're merely using Django's *model* permissions.

Django doesn't provide a way to test for object permissions, so rules has to provide its own template tag. Check here: https://github.com/dfunckt/django-rules#rules-and-permissions-in-templates

This will check *all* authentication backends, not only rules, so it can completely replace Django's static ``perms`` var -- i.e. you may use it to check for any permission.

**Comment by highpost** [comment]
Hi @dfunckt, thanks again for your help. I've fixed most of my problems with my views, but I do have a problem/misunderstanding with my predicate in rules.py:

```
@rules.predicate
def has_change_entry_perm(user):
    if rules.has_perm('blog.change_entry', user):
        return True
    else:
        return False

rules.add_perm('blog.change_entry', is_entry_author | is_editor | has_change_entry_perm)
```
This causes a recursion error. So I'm not sure how to create a predicate that tests for a specific permission.

**Comment by highpost** [comment]
I made another attempt, but I'm definitely missing something about has_perm. I'm getting a RecursionError in various efforts with the can_change_entry predicate. :(

**Comment by dfunckt** [comment]
You're calling rules back inside your predicate, which ends up calling your predicate again, hence the recursion error.

You don't need the ``has_change_entry_perm`` predicate. The check whether the user has model-level permissions (i.e. to change any entry) is done automatically for you by Django's default authentication backend.

**Comment by highpost** [comment]
I'm glad to say that I finally got it working. Once all the pieces are in the right place it makes sense.

I will follow this up with some documentation that can either go in a blog post or you can absorb it. I've also begun writing some pytest-based tests. I will have some questions for that, but the hardest part is behind me.

Thanks for your help.

https://github.com/highpost/rules-testapp

**Comment by ibnbay99** [comment]
Hi Highpost, i want to ask about your testapp...
I tested the rules-version...
It always error "AttributeError: 'module' object has no attribute 'predicate' " at blog/rules.py

Thanks...
