### ISSUE TITLE
Making rules work with CreateView

### ISSUE THREAD

**Issue by bcoover** [dfunckt/django-rules#39]
Not sure this is really an issue, but good for your documentation:
By default I have found rules don't work with CreateView because there is no object instance yet, so it throws a PK error. However, I have defined rules as such that will accept just the user object and will return the appropriate True/False. I really needed some security rules on the CreateView, so I started messing with the get_object function (unused for CreateView) and I made this work by adding the following function '**get_object**' to the CreateView class:

`
class CustomCreateView(PermissionRequiredMixin, CreateView):
    """ other stuff """
    def get_object(self):
        pass
`

Now I'm trying to get this working with ListView, which is proving to be a bit more difficult...

**Comment by dfunckt** [comment]
The error you get probably isn't from Rules, because it explicitly [handles the case where there's no `get_object` method](https://github.com/dfunckt/django-rules/blob/master/rules/contrib/views.py#L42-L46). As a result, your predicates should be called with the user instance only and no object, without having to add an empty `get_object` method to your view.

**Comment by bcoover** [comment]
Interesting, then as this returns None, should it throw the pk error, or just continue without it? I made sure that my rule predicate only had user, and no other params...

The error is:
`Lookup field 'pk' was not provided in view kwargs to 'UserAccountCreate'
`

and my code is:

`
@rules.predicate
def add_company(user):
    if user.is_staff:  # case: global admin, sees everything
        return True
    elif user.is_company_admin:
        if user.company.is_partner:  # case: partner, only see the companies they are partner for
            return True
    else:
        return False
`

**Comment by dfunckt** [comment]
Can you paste the exception stacktrace?

**Comment by bcoover** [comment]
Environment:


Request Method: GET
Request URL: https://www.rettach.com/manage/company/new/

Django Version: 1.9.9
Python Version: 3.4.5
Installed Applications:
('django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'custom_user',
 'rest_framework',
 'captcha',
 'widget_tweaks',
 'djcelery',
 'autofixture',
 'rules.apps.AutodiscoverRulesConfig',
 'platform_settings',
 'app_core',
 'website',
 'webapp',
 'backend_services',
 'API',
 'business')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')



Traceback:

File "/usr/local/lib/python3.4/site-packages/vanilla/model_views.py" in get_object
  54.             lookup = {self.lookup_field: self.kwargs[lookup_url_kwarg]}

During handling of the above exception ('pk'), another exception occurred:

File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.4/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.4/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/mixins.py" in dispatch
  90.         if not self.has_permission():

File "/usr/local/lib/python3.4/site-packages/rules/contrib/views.py" in has_permission
  49.         obj = self.get_permission_object()

File "/usr/local/lib/python3.4/site-packages/rules/contrib/views.py" in get_permission_object
  44.             return self.get_object()

File "/usr/local/lib/python3.4/site-packages/vanilla/model_views.py" in get_object
  57.             raise ImproperlyConfigured(msg % (lookup_url_kwarg, self.__class__.__name__))

Exception Type: ImproperlyConfigured at /manage/company/new/
Exception Value: Lookup field 'pk' was not provided in view kwargs to 'CompanyCreate'

**Comment by dfunckt** [comment]
I'm guessing that you missed to name the `pk` capture group in your urlconf and your view raises.

In any case this isn't related to rules, so I'll close the issue. Feel free to reopen if it turns out rules-related.

**Comment by bcoover** [comment]
Ok, thanks, there is no PK, because this is a createview

**Comment by dfunckt** [comment]
Right, sorry. The exception is raised from here: https://github.com/tomchristie/django-vanilla-views/blob/master/vanilla/model_views.py#L57 which is named `GenericModelView`, which `CreateView` probably inherits from. I'm not familiar with django-vanilla-views to be of help, but it might make sense to raise the issue there.

**Comment by bcoover** [comment]
Thanks!

**Comment by dfunckt** [comment]
OK, now I see what exactly happens. Your custom view inherits from `PermissionRequireMixin` and `CreateView`, which inherits from `GenericModelView` which defines a `get_object()` method. The permission mixin ends up calling `get_object` as expected, but `GenericModelView.get_object` only expects to be called with a PK, i.e. not in a create view.

The solution is either to raise an issue with `django-vanilla-views` to either remove `get_object` from `GenericModelView`, or add an empty `get_object` method to the `CreateView`.

A temporary workaround is what you already do: specify an empty `get_object` method in your custom view.
