### ISSUE TITLE
Django 1.10.4 autodiscover for rules.py modules failed

### ISSUE THREAD

**Issue by pyzenberg** [dfunckt/django-rules#49]
Replaced `'rules',` with `'rules.apps.AutodiscoverRulesConfig',` on `INSTALLED_APPS` settings to enable auto discover mode of `rules.py` modules as docs said and got this error:

`ImportError: No module named 'rules.apps.AutodiscoverRulesConfig'; 'rules.apps' is not a package`

P.S: I'm using Python 3.5.2 inside venv

**Comment by dfunckt** [comment]
If you installed via pip, can you make sure you actually did `pip install rules` and not `pip install django-rules`?

**Comment by pyzenberg** [comment]
Installed it via `pip install rules` and `pip freeze` gave `rules==1.1.1` too.

**Comment by dfunckt** [comment]
@pyzenberg , I haven't managed to reproduce the issue, can you please post the exception traceback or any other that might help identify the issue?

**Comment by dfunckt** [comment]
Haven't heard back so I assume it's not an issue anymore. Closing. Feel free to open the issue again if you still face problems with rules.
