### ISSUE TITLE
Release confusion

### ISSUE THREAD

**Issue by beruic** [dfunckt/django-rules#51]
Visiting https://github.com/dfunckt/django-rules/releases it seems like `v1.1.1` is the latest release, but there is also a `v1.2.0`, which also seems available on PyPI. What is the latest official (stable?) release, and what changed in `v1.2.0`?

**Comment by dfunckt** [comment]
The definitive source for the latest release and changelog is the project's README.

I released 1.2.0 a few weeks ago, but forgot to tell Github about it. It's fixed now, you may also find the changelog there. Sorry for the confusion.
