### ISSUE TITLE
Is predicates invocation too magic ?

### ISSUE THREAD

**Issue by ticosax** [dfunckt/django-rules#6]
Hi,
I'm raising a question here before submitting any pull request.
I think there is a design issue with Predicate.test(), because if I defined my predicate to accept only
two positional arguments and the caller gives only one argument, my predicate will be called with None for the second argument.

```python
@rules.predicate
def are_equal(a, b):
  return a == b

rules.add_rule('test_this', are_equal)
rules.test_rule('test_this', 'a', 'a') # OK there is two positional argument
rules.test_rule('test_this', 'a')  # why b is None in this case ??
```
This behaviour troubles me, I do not know yet how it should behave, but I would like, first, to hear from you.
Do you think there is room for improvement ?

**Comment by dfunckt** [comment]
This issue is now resolved by merging #15
