### ISSUE TITLE
Django 1.11 missing in tests

### ISSUE THREAD

**Issue by dyve** [dfunckt/django-rules#60]
There is no Django 1.11 in the test matrix. Is this project still alive and being kept up to date with new Django releases?

**Comment by dfunckt** [comment]
Hello, yes the project is alive. I'm not following Django closely lately so rules could really benefit from contributions by the community in this regard.

**Comment by dyve** [comment]
The tests succeed on Django 1.11 so it'd be a matter of updating the Travis and tox matrix. I could do a PR for that.

We are considering django-rules for our project, but if you are not following Django closely anymore, there seems to be a risk the project might be abandoned.

**Comment by dfunckt** [comment]
Yes please, a PR would be most welcome.

Don't worry it won't be abandoned any time soon, and even if it would, it's like 80 lines of simple code that anyone could pick up and move on with.

**Comment by rixx** [comment]
By now, adding a pre-release of Django 2.0 might be worthwhile, too, to see if there are any upcoming issues (or to boast of compatibility if there are none :wink:).

**Comment by dfunckt** [comment]
Fixed in 1.3.0

**Comment by dyve** [comment]
👍
