### ISSUE TITLE
Global superuser override?

### ISSUE THREAD

**Issue by shacker** [dfunckt/django-rules#62]
I need to create a lot of rulesets in a lot of models, and it appears that I will need to add an is_superuser predicate to every single one, which is not very DRY. Is there a way (or a best practice) to grant full access to superusers on everything touched by rules?

**Comment by dfunckt** [comment]
Hello, you could provide a custom auth backend that checks for the `is_superuser` attribute and returns `True`, as here: https://github.com/dfunckt/django-rules/blob/master/rules/permissions.py#L28

**Comment by njunxuan** [comment]
Not sure if this should be happening, but it seems that if a user is a superuser, the user is not subject to `django-rules`. I am using Django 2.0 with a CBV and `PermissionRequiredMixin`. In the console, the predicate is not being logged at all.

Is this supposed to be the default behaviour? Thank you.

**Comment by klumme** [comment]
I was just chasing what appeared to be a bug in my project, and found this was the case as well.

> Not sure if this should be happening, but it seems that if a user is a superuser, the user is not subject to `django-rules`. I am using Django 2.0 with a CBV and `PermissionRequiredMixin`. In the console, the predicate evaluation is not being logged at all.
> 
> Is this supposed to be the default behaviour? Thank you.

**Comment by dfunckt** [comment]
Yes, this is expected behaviour and is related with how Django handles permissions: https://github.com/django/django/blob/master/django/contrib/auth/models.py#L265

If you think about what a superuser is, it also makes sense. The workaround is to just not assign superuser status to users you don’t want to have full permissions, but grant a role instead.

**Comment by klumme** [comment]
@dfunckt That does make sense, thanks for clarifying!
