### ISSUE TITLE
assignment_tag is removed in django-2.0

### ISSUE THREAD

**Issue by rixx** [dfunckt/django-rules#69]
Quoting the [release docs](https://docs.djangoproject.com/en/2.0/releases/1.9/#deprecated-features-1-9):

> Django 1.4 added the assignment_tag helper to ease the creation of template tags that store results in a template variable. The simple_tag() helper has gained this same ability, making the assignment_tag obsolete. Tags that use assignment_tag should be updated to use simple_tag.

As this prevents a timely upgrade to Django 2.0 for me, I'd ask you to consider merging a PR and releasing a new version soon-ish.

**Comment by dfunckt** [comment]
Fixed in 1.3.0
