### ISSUE TITLE
rules.contrib.views.PermissionRequiredMixin hides coding errors from the developer

### ISSUE THREAD

**Issue by delroth** [dfunckt/django-rules#73]
```
        try:
            # Requires SingleObjectMixin or equivalent ``get_object`` method
            return self.get_object()
        except AttributeError:  # pragma: no cover
            return None
```

If the `get_object()` implementation has a bug that ends up causing AttributeError, the mixin gobbles it, which can lead to a very confusing result and debugging experience :)

Instead of looking at side effects of calling a missing method, what about using `hasattr`?

**Comment by dfunckt** [comment]
Fixed in 24e04edc0e, shipped with rules-1.4. Thank you!
