### ISSUE TITLE
Drop support for Django < 1.11

### ISSUE THREAD

**Issue by lorddaedra** [dfunckt/django-rules#75]
![](https://www.djangoproject.com/s/img/release-roadmap.e844db08610e.png)

**Comment by naringas** [comment]
django 1.11 is LTS (Long Term Support)
IMO support for it shouldn't be dropped until 2.2 LTS is released

**Comment by rpkilby** [comment]
@naringas - the OP is suggesting that support for versions *before* 1.11 be dropped, not for 1.11 itself.

**Comment by dfunckt** [comment]
"Fixed" in rules 2.0.
