### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by dyve** [dfunckt/django-rules#76]
We use this package @zostera, thanks for making this. Would a PR that does a little cleanup be welcome. I'd suggest:

- get rid of nose (last release was over 2 years ago)
- drop unsupported Python and Django combinations
- fix deprecation warning where possible

**Comment by dfunckt** [comment]
@dyve yeah, it’d be great to have a PR for these. I guess dropping support for legacy django/python versions means a major version bump, which I’ve tried to delay in order to include a few other breaking changes, but I think we can go ahead.

**Comment by dfunckt** [comment]
Fixed in rules 2.0 -- kudos @rpkilby

**Comment by dyve** [comment]
Thx all, turned out I didn't have the time to take this one on, great to see these changes.
