### ISSUE TITLE
Consider joining project to jazzband

### ISSUE THREAD

**Issue by bpereto** [dfunckt/django-rules#91]
Are you open for more contributiors?
might join [jazzband](https://jazzband.co)

**Comment by raratiru** [comment]
Just came in the issues tab to suggest that [django-packages](https://djangopackages.org/packages/p/django-rules/) is not aware that this project supports python3 neither its development status.

Reading this invitation, I got happier.

**Comment by dyve** [comment]
We @zostera appreciate all the hard work by @dfunckt. We are actively using this package in several projects and would be interested in helping out. Handing the project over to jazzband.co might also be an interesting opportunity.

**Comment by dfunckt** [comment]
Hello @bpereto, I'm happy to accept contributions but I do not consider joining an organisation relevant. I really appreciate your offer and work at Jazzband but I have to unfortunately decline.

@raratiru the project you linked is not correct -- for some mysterious reason, the URL for `rules` in django-packages is https://djangopackages.org/packages/p/admin/ (note the slug "admin" :/)

**Comment by dyve** [comment]
@raratiru django-packages refers to https://github.com/maraujop/django-rules (last update 8 years ago)

**Comment by raratiru** [comment]
@dfunckt  OK, got it, the name in packages is `rules` (as in `pip install`) not `django-rules` and it has the slug `admin`.  

No matter what, this app rocks. Thank you!
