### ISSUE TITLE
current build is failing

### ISSUE THREAD

**Issue by guyjacks** [dfunckt/django-rules#92]
Is this project still actively maintained?  I'm asking because the current build is failing.

**Comment by dfunckt** [comment]
Hey, the build is indeed failing but if you look closely it’s only tox packaging that started failing in the latest build for no apparent reason. I had a look but it only seems to be failing on Travis if I remember correctly and didn’t care.

**Comment by guyjacks** [comment]
Ok, I looked at Travis and thought the same thing.

**Comment by dfunckt** [comment]
Fixed by 4eacdba35
